### ISSUE TITLE
SparseDataFrame - kryzys Egzystencjalny 

### ISSUE THREAD

**Issue by Shinigami072** [monikaapiekarska/DataFrame#1]
Problemem w zobaczeniu sensu jest nie jako jest to jak zaimplemementowałaś SparseDataFrame

W założeniu miał to być Kontener do przechowywania wielu danych -z których wiele jest identycznych

Jako że jest DataFrame powinien umożliwiaś dostęp do nich przez te same metody co normalny DataFrame tzn - jeśli stworzymy SDF i DF i możemy włożyć i wyjąć z nich te same Obiekty - w taki sam  sposób

kluczem w zrozumieniu jest tutaj Fakt że SDF **JEST** DF - więc jeślibyśmy przekazali go do jakiejś funkcji która działa na DF - z użyciem jej metod publicznych, to mogłaby ona działać bez problemu, czy jakichkolwiek zmian - nie koniecznie by było to optymalne korzystanie ze struktury ale możliwe.

w czym SDF jest lepszy od DF:
+ MA Dużo lepszązlożoność pamięciową w stosunku dla Tradycyjnego DF - załuż że masz DF składający cię z 1000 wierszy o tej samej wartośći - SDF przechowywuje 1 rząd domyślnych wartości i licznik ile ich faktychnie jest, natomiast DF przechowywuje każdą z nich z osobna

w czym jest Gorszy od DF:
+ wolniejszy czas dostępu do Wartości - jeśli przechowywujesz tylko część z nich - to musisz jakoś dojśc do tego które z nich pokazać użytkownikowi że są w danym wierszu

Jak wygląda twoja implementacja w porównaniu:
======
jest to DF - z dodatkową funkcją - zamieniającą  go na pełnowymiarowego DF
Jeśli chce się skorzystać z pamięciowych optymalizacji trzeba by go było samemu modyfikować bo nie masz żadnych akcesorów zmodyfikowanych

**Comment by monikaapiekarska** [comment]
"kryzys egzystencjalny" - czy Ty już wpadasz w depresję patrząc na mój kod? XDDD
To coś czuję, że z tym będzie dużo roboty... Zostawię to na potem
