### ISSUE TITLE
podobno wrócisz do tego

### ISSUE THREAD

**Issue by Shinigami072** [monikaapiekarska/DataFrame#2]
tu mam tylko taki komentarz - popatrzile razy piszesz ten sam kod - który różni się tylko jedną operacją jaka wykonujesz - czy nie lepiej by było napisać jedną funkcję - która realizowałaby wszystkie możliwe operacje (np zmienić value by miał możliwość zrobić coś takiego), a pożniej ewentualnie dodać te wszystkie funcjke jako wywołanie jej z jakimiś domyślnymi wartoścami? (Value,Ogólna funkcja,szczególna funkcja)

https://github.com/monikaapiekarska/DataFrame/commit/3a3d09834ea05072a9b4ebf3a3f3792344acde87#r31782880

**Comment by monikaapiekarska** [comment]
Zrobiłam czil xD
